python3: can't open file '/dtu-compute/macaroni/Task_WMM_ACGMM_HMM/submitfiles/realdata_regu_K_LR.py': [Errno 2] No such file or directory

------------------------------------------------------------
Sender: LSF System <lsfadmin@hpc.dtu.dk>
Subject: Job 15439345: <NONAME> in cluster <dcc> Exited

Job <NONAME> was submitted from host <gbarlogin1> by user <ansol> in cluster <dcc> at Sat Feb 25 13:55:43 2023
Job was executed on host(s) <n-62-31-22>, in queue <hpc>, as user <ansol> in cluster <dcc> at Sat Feb 25 13:55:46 2023
</zhome/61/4/109113> was used as the home directory.
</dtu-compute/macaroni/Task_WMM_ACGMM_HMM/submitfiles> was used as the working directory.
Started at Sat Feb 25 13:55:46 2023
Terminated at Sat Feb 25 13:55:48 2023
Results reported at Sat Feb 25 13:55:48 2023

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
python3 realdata_regu_K_LR.py $regu $LR

------------------------------------------------------------

Exited with exit code 2.

Resource usage summary:

    CPU time :                                   1.18 sec.
    Max Memory :                                 -
    Average Memory :                             -
    Total Requested Memory :                     1024.00 MB
    Delta Memory :                               -
    Max Swap :                                   -
    Max Processes :                              -
    Max Threads :                                -
    Run time :                                   2 sec.
    Turnaround time :                            5 sec.

The output (if any) is above this job summary.

